### ISSUE TITLE
Strong name

### ISSUE THREAD

**Issue by andrewdavey** [andrewdavey/postal#18]
@blowdart on twitter is asking for a strong name

**Comment by robitar** [comment]
Second this, I've set it up locally and done all the messy InternalsVisibleTo stuff, but the test project wont build because 'Should' isn't strong named either. I left it there and just got on with the job at hand.

Would be great to get it sorted, I hate having to maintain a dependency outside of nuget nowadays, could the Should class just be copied directly into the test project?

**Comment by andrewdavey** [comment]
Version 0.6.2 is now strongly named and in nuget. Please give it a go and make sure everything is working for you.

(Sorry this took so long to sort out - I've been side tracked by many other projects!)

**Comment by robitar** [comment]
No worries, I'm swamped myself.

I tried out the nuget package, but it looks like Postal.dll has no strong name, it also looks like the assembly version is still 0.6.0.0, is it possible the wrong build snuck into the nuget package?

Also I forgot to ask you to put in a CLSCompliant(true) attribute in the AssemblyInfo, otherwise the compiler complains when you derive from Email in an assembly which does have it.

Thanks for all the great work, really looking forward to using this one.

**Comment by andrewdavey** [comment]
Hmm, I seem to fail at nuget! I'll try to take a look this evening.

**Comment by robitar** [comment]
No worries, I'll check it out when it goes up again

**Comment by andrewdavey** [comment]
Please try v0.6.3. That should now have the new, strong named, DLL as well as being CLSCompliant.

**Comment by robitar** [comment]
That did it, thanks for the fast turnaround, appreciated.
