### ISSUE TITLE
sending with amazon ses

### ISSUE THREAD

**Issue by rebootd** [andrewdavey/postal#28]
Not so much an issue as a question... I'm using Postal with a site hosted on ec2, but have just discovered that the app breaks when I put the <stmp> config section in the web.config on ec2. I don't know why, but I'm trying to get something working fast. 

Is it possible to send mail message from Postal using a 3rd party api like amazon SES? 

Thanks

**Comment by andrewdavey** [comment]
What exception do you get?

Postal does not currently have support for Amazon SES built-in. You will need to create your own implementation of Postal's IEmailService. You can use the existing implementation to get started: https://github.com/andrewdavey/postal/blob/master/src/Postal/EmailService.cs
Then you should be able to call Amazon's API instead of the SmtpClient object.

**Comment by gwilliams** [comment]
I threw together https://github.com/gwilliams/Postal.AmazonSES to add SES support for Postal - if this is still of interest to anyone.

**Comment by abarberis** [comment]
@andrewdavey Amazon SES now has full support for sending mail through native .NET classes. There is no need to do anything special for Postal to work. If you set enableSsl="true" and port="587" in Web.config it will work. You can close out this issue.

**Comment by andrewdavey** [comment]
Thanks!
