### ISSUE TITLE
Apostrophe in email address

### ISSUE THREAD

**Issue by ganeshjr** [andrewdavey/postal#77]
I get the following error message when the "to" email address contain apostrophe:

An invalid character was found in the mail header: ';'.

Is there a work around to this issue?

I came across this on the MSDN: http://social.msdn.microsoft.com/Forums/en-US/84dd5b66-f68d-4b0c-823f-25aa7c7b4d6b/apostrophe-in-email-address?forum=netfxnetcom

In Postal, the EmailParser creates MailMessage object with the default constructor. The MSDN thread suggests using a different constructor.

Thanks

**Comment by p10tyr** [comment]
Thats a semicolon not and apostrophe ?! Any way I thought that you could separate multiple emails with commas in Postal. email1,email2,emailx

**Comment by ganeshjr** [comment]
The error message displays a semi colon for some reason. For example, the error is displayed when the "To" email address is o'connor@somedomain.com which is a valid email address according to RFC standard.

**Comment by p10tyr** [comment]
Yes. This seems to be a bug in either Postal or the .NET SMTP Mail sender that Postal is wrapped around. (I think Postal is using the default 'old' constructor of MailMessage as you suggested) 

Gmail and other big free email providers don't allow you to create emails with these symbols because of security issues.

You can send an emial to 

{piotr'kula}@kula.solutions

(as you can see not even markdown translated that to an email adress instead it thinks its a shortcut)

and you should get an Auto reply. I tested it in outlook using ISP and Gmail to send emails. 

![image](https://cloud.githubusercontent.com/assets/1249683/3586071/a569d12e-0c2c-11e4-83e0-a68cf533784d.png)

**Comment by vincentvanderwalt** [comment]
Hi I've just migrated our password reset functionality to postal. We have loads of irish surname users and they're all failing with the above error.

Is there some work around for this ? Or do I need to stop using postal and fall back to using smtpclient which does support it via the different constructor?

Vinny

**Comment by ganeshjr** [comment]
Hi Vinny,
Try using email address that is not encoded in the email template view. Something like this:
**To: @Raw**(_Model.To_)

After downloading the Postal source and debugging, we noticed that the apostrophe in the email address gets encoded (I think it was `&#39;`). This seems to be the reason for semicolon in the misleading error message.

Hope this helps.

-Ganesh

**Comment by vincentvanderwalt** [comment]
Hi Ganesh

Thanks for the tip. I can confirm that this works fine.

Vinny

**Comment by ganeshjr** [comment]
Closing the issue.
Solution: Do not use encoded email address in the view.

To: @Raw(Model.To)
